### ISSUE TITLE
html修正

### ISSUE THREAD

**Issue by BASARA0826** [hew2023fgroup/HEW2023_Fgroup#138]
・レイアウト変更機能の関係でカテゴリーとサイトタイトルの文字色の初期値が白→黒になり見づらい
・商品一覧表示の「おすすめ商品」の文字列を妥当な文字列に変更
・マイページのお気に入り一覧のアイコンをハートからブックマークに変更
・レイアウト編集機能のcssを整える
とりあえず自分が気になったのはこのあたりなのでこれ以外に気になったところもあれば修正ヨロシク

**Comment by hikaru1309** [comment]
・商品一覧表示の「おすすめ商品」の文字列を妥当な文字列に変更
・マイページのお気に入り一覧のアイコンをハートからブックマークに変更
はfeature#135でやっているので、そちらからプルリクします。
