### ISSUE TITLE
ログイン・新規登録画面の入力制限・ボタン調整

### ISSUE THREAD

**Issue by hikaru1309** [hew2023fgroup/HEW2023_Fgroup#92]
ログイン・新規登録画面の入力制限・ボタン調整

**Comment by BASARA0826** [comment]
登録内容確認画面のボタン間の灰色をなくす
戻るボタンのみのときボタン表示を真ん中にする
ユーザーネーム、メールアドレスの文字折り返しをなくす
ログイン機能の警告文を「ログインできませんでした、ご確認の上もう一度お試しください」に変更する
